# Generated by Django 3.1 on 2020-08-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienvenido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='descripcion',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
